name: 
title: Homepage
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: Zofia-Leszczynska/just-the-docs

color_scheme: dark



aux_links:
  "Source repository on GitHub":
    - "//github.com/Zofia-Leszczynska/zofia-leszczynska.github.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw)."